### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by azsao** [JOY6IX9INE/TikTok-Mass-Reporter#8]
Traceback (most recent call last):
  File "/home/alao/TikTok-Mass-Reporter/main.py", line 1, in <module>
    import tls_client, httpx, requests
  File "/home/alao/TikTok-Mass-Reporter/venv/lib/python3.12/site-packages/tls_client/__init__.py", line 15, in <module>
    from .sessions import Session
  File "/home/alao/TikTok-Mass-Reporter/venv/lib/python3.12/site-packages/tls_client/sessions.py", line 5, in <module>
    from .settings import ClientIdentifiers
  File "/home/alao/TikTok-Mass-Reporter/venv/lib/python3.12/site-packages/tls_client/settings.py", line 1, in <module>
    from typing_extensions import Literal, TypeAlias
ModuleNotFoundError: No module named 'typing_extensions'

Appears to be an issue with the modules

**Comment by JoyNath1337** [comment]
pip install typing_extensions
